name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v4

   # Install GCC 14 and set it as the default 
    - name: Install GCC 14
      run: |
        sudo apt update
        sudo apt install software-properties-common -y
        sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
        sudo apt update
        sudo apt install gcc-14 g++-14 -y # Install GCC and G++ 14.
        sudo apt-get install -y pkg-config
        sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-14 100 --slave /usr/bin/g++ g++ /usr/bin/g++-14 # Set GCC 14 as the default.

    # Build project
    - name: Build project
      run: |
        make

    # Run tests
    - name: Run NIST tests
      run: make test

    # Run examples
    - name: Run examples
      run: |
          cd examples
          make
          cd bin
          for exe in *; do
            if [[ -x "$exe" ]]; then
              echo "Running $exe"
              ./"$exe"
            fi
          done
